### ISSUE TITLE
N/A: version "default" is not yet installed

### ISSUE THREAD

**Issue by cig0** [passcod/nvm-fish-wrapper#10]
Hello @passcod 
After following your instructions to the letter I got this:

```
~/.d/h/n/.c/f/nvm-wrapper ‹master›> source ~/.config/fish/nvm-wrapper/nvm.fish
N/A: version "default" is not yet installed
/usr/bin/rm: remove 1 argument recursively?
```

OS: Fedora 21
Fish: 2.1.1

**Comment by passcod** [comment]
Comment out the last line of `~/.config/fish/nvm-wrapper/nvm.fish`, try again, install a version and alias it as default, then put it back in.
