### ISSUE TITLE
Could Not autoload item 'nvm'

### ISSUE THREAD

**Issue by steve-ross** [passcod/nvm-fish-wrapper#11]
Getting this error on the mac

```
> nvm
fish: Could not autoload item 'nvm', it is already being autoloaded. This is a circular dependency in the autoloading scripts,
please remove it.
test: Missing argument at index 2
```

When I remove the last line https://github.com/passcod/nvm-fish-wrapper/blob/6eb9bc8c6e80f473ff6fe0cf1f062d79c2360916/nvm.fish#L104 it goes away:

```
nvm use default 2>&1 >/dev/null
```

I'm using oh my fish if that matters

**Comment by passcod** [comment]
Err, I have no idea what autoloading is and why it's complaining (is it an oh-my-fish thing?), but given that this line is causing all sorts of trouble (#10), I'll remove it from the release.
