### ISSUE TITLE
Sourcing is not needed?

### ISSUE THREAD

**Issue by leebrooks0** [passcod/nvm-fish-wrapper#12]
If I place nvm.fish in ~/.config/fish/functions, it gets loaded automatically.

**Comment by passcod** [comment]
Do you know if that's a new feature in the fish shell or if it's been there a while?

**Comment by nanoxd** [comment]
It's been there for a while.

**Comment by nanoxd** [comment]
Since 2012 according to [git history](https://github.com/fish-shell/fish-shell/commit/e94e1cc72fa6eb95549493788e72219922785733)

**Comment by passcod** [comment]
Closing down (see Readme).
