### ISSUE TITLE
Garbage output at the end of nvm commands

### ISSUE THREAD

**Issue by brandonweiss** [passcod/nvm-fish-wrapper#14]
This is weird, but when I run an `nvm` command I get weird output and my prompt doesn't return. I have to hit enter to exit the command and return to my prompt. Does that make sense? It looks like this:

``` fish
> nvm use 0.12
Now using node v0.12.5 (npm v2.11.2)
examine files in directory /var/folders/gb/2px5x_ys5cz6r59640377k800000gn/T/nvm-wrapper.Zc3v3eyZ? 
```

**Comment by passcod** [comment]
Are you on OS X? Linux? What's your fish config?

**Comment by passcod** [comment]
A google search on the message reveals that this is because you aliased `rm` to `rm -i`. The wrapper calls `rm -r` on the temp folder as cleanup and your alias makes this `rm -i -r` which proceeds to ask you whether you really want to do that.

Closing as not-a-bug.

**Comment by brandonweiss** [comment]
Sorry, I completely forgot to include any relevant information.

Yep, you're totally right. Although I didn't alias it—I wrote a fish function that wraps `rm` specifically so it wouldn't affect external scripts.

I believe when executing commands in a fish script it's best to use the `command` command to ensure a command doesn't collide with a fish function. Would you be open to me changing the [removal command](https://github.com/passcod/nvm-fish-wrapper/blob/46f8cee3ec1a1bc5c4b0a1a7511654a705180c4f/nvm.fish#L100) to `command rm -r $tmpdir`?

**Comment by passcod** [comment]
Sure, as well as any other commands that may be affected if you can. Just open a PR :)
