### ISSUE TITLE
installation fails while using `source` in config.fish

### ISSUE THREAD

**Issue by tushar-rishav** [passcod/nvm-fish-wrapper#18]
Reloading the shell after adding the below line to `config.sh`  throws a `Unknown command 'source'` error.

``` sh
source ~/.config/fish/nvm-wrapper/nvm.fish
```

The bug is in fish shell that has been reported [here](https://github.com/fish-shell/fish-shell/issues/794) and a possible hack for this [here](https://github.com/fish-shell/fish-shell/issues/841). It would be helpful for new comers if we could mention about it in `README.md` as well. Maybe add/replace the above line with this -

``` sh
.  ~/.config/fish/nvm-wrapper/nvm.fish

```

**Comment by alex7kom** [comment]
It's not a bug, you use the old version of fish shell. Also, this wrapper is no longer maintained, see README.

**Comment by tushar-rishav** [comment]
Oh. Didn't notice that. Got upgraded to the latest version and everything is working fine now. 
Thankyou.
