### ISSUE TITLE
Submit to oh-my-fish

### ISSUE THREAD

**Issue by keithamus** [passcod/nvm-fish-wrapper#4]
Thanks @passcod for the awesome wrapper lib! You should totally send a PR to the fine maintainers at [oh-my-fish](https://github.com/bpinto/oh-my-fish) and get it placed as a plugin. Alternatively, if you permit me to I can make the PR.

**Comment by passcod** [comment]
Please do, I don't use oh-my-fish myself. Ref your PR to this issue so I know its status :)

**Comment by passcod** [comment]
As pointed out by @derekstavis in creationix/nvm#303, [foreign-env](https://github.com/oh-my-fish/plugin-foreign-env) in Oh My Fish can achieve the same behaviour as **bass** and therefore this wrapper :)

**Comment by derekstavis** [comment]
Now there's also https://github.com/derekstavis/plugin-nvm which include nice completions.
