### ISSUE TITLE
OS X  MANPATH breaks after sourcing 

### ISSUE THREAD

**Issue by externl** [passcod/nvm-fish-wrapper#7]
If I load up my fish shell without sourcing nvm.fish with empty MANPATH, I can get system man pages. Once I source nvm.fish, everything is gone.

```
$ echo $MANPATH
$ man git > /dev/null; and echo "success"
success
$ source ~/.nvm-fish-wrapper/nvm.fish
$ echo $MANPATH
/Users/joe/.nvm/versions/io.js/v1.2.0/share/man
$ man git
No manual entry for git
```

**Comment by passcod** [comment]
I think that fixes it. Tell me if it's otherwise.

**Comment by blazeworx** [comment]
This update breaks the wrapper on my OSX machine, it appears as though `manpath` does not have a `-g` option on OSX (at least on 10.9.5 which this machine is running). 

![image](https://cloud.githubusercontent.com/assets/4718238/6378344/cdd12e78-bcf8-11e4-998d-4a607bbd7436.png)

When I remove the `-g` flag [on this line](https://github.com/passcod/nvm-fish-wrapper/blob/master/nvm.fish#L73) it works

**Comment by passcod** [comment]
We do need to use `-g` on Linux, though, otherwise it breaks there. I'll try to fix it up this weekend.

**Comment by passcod** [comment]
Closing down (see Readme).
